# This recipe defines the structure and contents of your custom ShardOS image.
# It uses the Universal Blue (UB) framework and various modules.

# -------------------------------------------------------------
# BASE IMAGE
# -------------------------------------------------------------
name: shardos
description: The custom operating system image for ShardOS.
base-image: ghcr.io/ublue-os/kinoite-main # Or your preferred base image

# -------------------------------------------------------------
# IMAGE TAGS & ARCHITECTURE
# -------------------------------------------------------------
# Define which architectures to build for (e.g., x86_64, aarch64)
# arch: x86_64

# -------------------------------------------------------------
# MODULES
# -------------------------------------------------------------
modules:

  # 1. CORE SYSTEM FILES
  # Merges files from the local 'files/system' directory into the OS root (e.g., /etc/motd)
  - type: files
    files:
      - source: system
        destination: /

  # 2. DNF PACKAGE MANAGEMENT (Install/Remove RPMs)
  - type: dnf
    # Packages to REMOVE from the base image
    remove:
      # Fix for Issue: Ensure Firefox and its language packs are removed
      - firefox
      - firefox-langpacks
    
    # Packages to INSTALL into the base image
    install:
      # VIRTUALIZATION & KVM (Host Hypervisor)
      - qemu-kvm
      - libvirt-daemon-config-network
      
      # USER TOOLS
      - micro # A terminal-based text editor
      - starship # A customizable prompt for the shell

  # 3. FLATPAK MANAGEMENT (Add/Remove Remotes and Apps)

  # Fix for Issue: Remove the default Fedora Flatpak remote to prevent confusing notifications
  - type: flatpak-remove
    remove:
      - remote: fedora

  # NEW: Install the Bazaar Flatpak app from Flathub
  - type: flatpak-install
    install:
      - app-id: io.github.kolunmi.Bazaar
        remote: flathub

  # 4. UJUST & UPDATES
  # Adds the ujust management utility
  - type: ujust

  # Configures automatic system updates
  - type: update-system
